version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "yarn install && yarn start"
    restart: "no"
    env_file:
      - ".env"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "bundle install && bin/rails tmp:clear && bin/rails server"
    restart: "no"
    env_file:
      - ".env"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
  postgres:
    image: postgres:12.11-alpine
    env_file:
      - ".env"
    healthcheck:
      test:
        [
          "CMD", "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
        ]
      retries: 3
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:7.0-alpine
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - redis-data:/data:rw
volumes:
  postgres-data:
  redis-data:
